### ISSUE TITLE
Cannot find Rosetta

### ISSUE THREAD

**Issue by biotech70** [JinyuanSun/Codes_for_FoldX#10]
Hi, how can I solve the following problem?
![ddgscan error](https://user-images.githubusercontent.com/73783725/206177877-3f37542a-f1b4-4066-81f4-0fb335b2f102.png)

**Comment by JinyuanSun** [comment]
You need to compile the MPI version of rosetta.

**Comment by biotech70** [comment]
ddgscan just work with mpi rosetta?

**Comment by JinyuanSun** [comment]
It is, for now. The `relax` takes a very long time if run sequentially. I scheduled some updates in Feb 2023. I may add a multi-threaded relax with the `relax.static.linuxgccrelease`.   
I made a quick fix to allow skipping the `relax` step, by setting the `-nstruct 0`. Update and try again.

My test command: 
```bash
DDGScan grape_phaseI 1pga.pdb A -T 20 -nstruct 0 -E rosetta -M run -S slow
```

**Comment by JinyuanSun** [comment]
> It is, for now. The `relax` takes a very long time if run sequentially. I scheduled some updates in Feb 2023. I may add a multi-threaded relax with the `relax.static.linuxgccrelease`. I made a quick fix to allow skipping the `relax` step, by setting the `-nstruct 0`. Update and try again.
> 
> My test command:
> 
> ```shell
> DDGScan grape_phaseI 1pga.pdb A -T 20 -nstruct 0 -E rosetta -M run -S slow
> ```

BTW, for a small protein with a high-quality structure (resolution < 2.0 Å), it is not a big problem to skip relax. For larger proteins or a high-quality structure unavailable, the relax might be necessary.
