### ISSUE TITLE
ERROR: Chain break detected! Transfer to AlphaFold.

### ISSUE THREAD

**Issue by wujialu** [JinyuanSun/Codes_for_FoldX#12]
Hi, how can I solve this error?
DDGScan grape_phaseI 7bnn.pdb B -E foldx -M run -T 40 -P CUDA -nruns 1 -fill -seq rcsb_pdb_7BNN.txt
![image](https://user-images.githubusercontent.com/81202232/218375448-0b7d92bc-8d18-4bb3-8b51-5fbe6a9594d8.png)

**Comment by JinyuanSun** [comment]
Which version did you use? The current release should not raise this error.

**Comment by JinyuanSun** [comment]
It's possible that updating to the newest version of DDGScan may resolve the issue and prevent the error message from appearing. I would suggest giving that a try first, and please let me know if you continue to experience any problems.

It seems that there is a large unmodeled region in your protein structure. And the loop built by Modeller may not be accurate enough for such a long region. You may want to consider refining the loop region using other modeling techniques (AlphaFold or ESMFold) to get a more accurate protein structure for further analysis.

**Comment by JinyuanSun** [comment]
If you want to focus on specific regions of interest, you can use the list_distribution option instead of grape_phaseI.

If you need any assistance in generating the posistion_list file, please let me know.
