### ISSUE TITLE
About ABACUS

### ISSUE THREAD

**Issue by Wendell407** [JinyuanSun/Codes_for_FoldX#13]
Sir, When I get the source code of ABACUS and run ABACUS_S1S2 script, the error information is like that:
![image](https://user-images.githubusercontent.com/124758415/231106339-d7642b73-5bf7-4522-b13b-7b72af1376eb.png)
but I can not find the 'dirLinux.txt', how can I solve this problem?

**Comment by JinyuanSun** [comment]
The `dirLinux.txt` file should be generated after running the `setup.sh` script provided by the ABACUS developers in the distribution package. To locate the file, first, verify if it is present in the ABACUS installation directory. Secondly, inspect the `~/.bashrc` file (or its equivalent on your system) to ensure that the `path/to/ABACUS/bin/` directory has been added to your system's path, and the environment variable `ABACUSPATH=path/to/ABACUS/` has been set correctly.

As I am not a developer for the ABACUS project, I recommend that you contact the ABACUS developers directly for assistance with this issue. They would be better equipped to guide you through the troubleshooting process and provide a solution.
